# -*- coding: utf-8 -*-
"""Data Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQjTFGm0MbfEFxD5s00nQDMkkO0DRMvC
"""

import pandas as pd

import pandas as pd

data = pd.read_excel('/content/Superstore.xlsx')
data

data.info()

data.describe(include="all")

missing_values = data.isnull().sum()
missing_values[missing_values > 0]

"""Data is clean"""

